server.port: 8080

logging:
#  file: logs/ci-manager.log
  level:
    org.springframework.web: info
    com.atsistemas: debug
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

gogs:
  user: ${GOGS_USER}
  passwd: ${GOGS_PASSWD}
  migrateContextPath: /api/v1/repos/migrate
  migrateUrl: 'http://${GOGS_SERVICE_HOST}:${GOGS_SERVICE_PORT}${gogs.migrateContextPath}'