server.port: 8080

logging:
#  file: logs/ci-manager.log
  level:
    org.springframework.web: info
    com.atsistemas: debug
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

  
gogs:
  user: ${GOGS_USER:gogs}
  passwd: ${GOGS_PASSWD:gogs}
  migrateContextPath: /api/v1/repos/migrate
  migrateUrl: 'http://${GOGS_SERVICE_HOST:localhost}:${GOGS_SERVICE_PORT:3000}${gogs.migrateContextPath}'
  
openshift:
  url: 'https://localhost:8443'
  user: developer
  passwd: any