server.port: 8080

logging:
#  file: logs/ci-manager.log
  level:
    org.springframework.web: info
    com.atsistemas: debug
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

gogs:
  host: ${GOGS_HOST}
  port: 3000
  contextPath: /api/v1/repos/migrate
  user: dani
  passwd: 1234
  migrateUrl: 'http://${gogs.host}:${gogs.port}${gogs.contextPath}'