swagger: '2.0'
info:
  version: '0.1-SNAPSHOT'
  title: 'ci-manager'
  description: 'ci-manager API'
produces:
  - application/json  
paths:
  '/projects':
    post:
      parameters: 
        - name: createProjectRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateProjectRequest'
      responses:
        201:
          description: Project created
          schema:
            $ref: '#/definitions/Project'
        404:
          description: Not found
        500:
          description: Internal server error
      
definitions:
  CreateProjectRequest:
    type: object
    properties:
      projectName:
        type: string
      repoUrl:
        type: string
    required:
      - projectName
      - repoUrl
     
  Project:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      name:
        type: string